Repository vnLab-Lodz/PubLab, pull requests merged in 2022-04, with the labels that each got.

#195 Fix a bug with devtolls extension installation
  package.json
  yarn.lock
Labels: bug, tooling

#199 Notification spawning system
  src/renderer/components/CloseButton/CloseButton.tsx
  src/renderer/components/Notification/Notification.tsx
  src/renderer/components/Notification/style.ts
  src/renderer/components/NotificationsOutlet/index.tsx
  src/renderer/components/NotificationsOutlet/style.ts
  src/renderer/components/Outlet/Outlet.tsx
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/Description/Description.tsx
  src/shared/redux/rootReducer.ts
  src/shared/redux/slices/notificationsSlice.ts
Labels: feature, front-end

#200 Fix filesystem errors
  src/main/api/settings/read.ts
  src/main/lib/publicationFinder.ts
  src/renderer/components/DirectoryPicker/DirectoryPicker.tsx
  src/renderer/components/Notification/Notification.tsx
  src/renderer/components/NotificationsOutlet/NotificationsOutlet.tsx
  src/renderer/components/Outlet/Outlet.tsx
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/FirstTime/FirstTime.tsx
  src/renderer/views/FirstTime/style.ts
  src/renderer/views/FirstTime/validationSchema.ts
  src/shared/redux/slices/notificationsSlice.ts
Labels: bug

#208 Improve PublicationModification type
  src/shared/redux/slices/loadPublicationsSlice.ts
Labels: refactor
