Repository vnLab-Lodz/PubLab, pull requests merged in 2022-09, with the labels that each got.

#246 Fix first time view logic
  src/main/git/gitAuthorization.ts
  src/renderer/components/App/App.tsx
  src/renderer/views/FirstTime/FirstTime.tsx
  src/shared/redux/helpers/utilSelectors.ts
  src/shared/redux/slices/currentViewSlice.ts
Labels: bug, fix

#251 Project server in side view
  package.json
  public/index.html
  src/main/api/index.ts
  src/main/api/publications/generate.ts
  src/main/api/server/clearCache.ts
  src/main/api/server/start.ts
  src/main/lib/configurationFileHandler.ts
  src/main/lib/publicationFinder.ts
  src/renderer/components/CustomRouter/redirects.ts
  src/renderer/components/IconButton/IconButton.tsx
  src/renderer/components/Terminal/Terminal.tsx
  src/renderer/components/Terminal/components/Output/Output.tsx
  src/renderer/components/Terminal/components/Output/style.ts
  src/renderer/components/Terminal/components/Toolbar/Toolbar.tsx
  src/renderer/components/Terminal/components/Toolbar/style.ts
  src/renderer/components/Terminal/style.ts
  src/renderer/components/Tooltip/Tooltip.tsx
  src/renderer/components/ViewContent/style.ts
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/Project/Project.tsx
  src/renderer/views/ProjectInfo/ProjectInfo.tsx
  src/renderer/views/Settings/Settings.tsx
  src/shared/redux/slices/loadPublicationsSlice.ts
  src/shared/types/api.ts
  src/shared/types/index.ts
  src/shared/utils/typeChecks.ts
  yarn.lock
Labels: feature, fix

#255 Project creation based on templates
  .storybook/__mocks__/fs.js
  .storybook/main.js
  package.json
  src/main/api/publications/generate.ts
  src/main/lib/gatsbyProjectGenerator.ts
  src/renderer/components/CollabPicker/CollabPicker.stories.tsx
  src/renderer/components/Languages/LanguagesPicker.tsx
  src/renderer/components/Notification/Notification.stories.tsx
  src/renderer/components/PackageManagerPicker/PackageManagerPicker.tsx
  src/renderer/components/RadioButton/RadioBtn.tsx
  src/renderer/components/RadioButton/RadioGroup.stories.tsx
  src/renderer/components/Switch/Switch.stories.tsx
  src/renderer/components/Switch/Switch.tsx
  src/renderer/components/TechnologiesPicker/TechnologiesPicker.tsx
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/AddProject/subcomponents/Steps/Steps.tsx
  src/shared/redux/slices/addPublicationWizardSlice.test.ts
  src/shared/redux/slices/addPublicationWizardSlice.ts
  yarn.lock
Labels: feature

#257 Files search
  src/renderer/components/PublicationHeader/PublicationHeader.tsx
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/Files/Files.tsx
  src/renderer/views/Files/subcomponents/FileExplorer/FileExplorer.tsx
  src/renderer/views/Files/subcomponents/FileSearchExplorer/FileSearchExplorer.tsx
  src/renderer/views/Files/subcomponents/FileTree/FileTree.tsx
Labels: feature

#260 Improve checkout when switching publications
  src/main/lib/gitRepoHandler.ts
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/ProjectsList/subcomponents/ProjectsTable/ProjectsTable.tsx
Labels: fix

#258 Sort files in human readable form
  src/renderer/views/Files/Files.tsx
Labels: feature, front-end

#259 Reinstate commit file grouping by dir path
  src/renderer/utils/formatPath.tsx
  src/renderer/views/Changes/subcomponents/ChangedFiles/FilesByFolder.tsx
  src/renderer/views/Files/subcomponents/FileSearchExplorer/FileSearchExplorer.tsx
Labels: bug, fix

#263 Collaborator list handling in respect to the current user
  src/renderer/components/CollabTable/CollabTable.tsx
  src/renderer/components/CollaboratorsPicker/CollaboratorsPicker.tsx
  src/renderer/components/TableCell/TableCell.ts
  src/renderer/internationalisation/locales/en/translation.json
  src/renderer/internationalisation/locales/pl/translation.json
  src/renderer/views/AddProject/AddProject.tsx
  src/renderer/views/AddProject/subcomponents/Steps/Steps.tsx
  src/renderer/views/Settings/Settings.tsx
  src/shared/redux/slices/addPublicationWizardSlice.ts
  src/shared/types/index.ts
Labels: front-end
